import type { ReactNode } from "react";
import type { BuildingPerformanceReportSnapshot } from "./buildingPerformanceReport.types";
import { displayText, formatMetric } from "./buildingPerformanceUi";
import { BuildingPerformanceTrendChart } from "./BuildingPerformanceTrendChart";
import { BuildingPerformanceBreakdownChart } from "./BuildingPerformanceBreakdownChart";

function Values({ rows }: { rows: [string, ReactNode][] }) {
  return <dl>{rows.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>;
}
function Unavailable({ section }: { section?: { error: string | null; loading: boolean; data?: unknown; query?: unknown } | null }) {
  return <p className="bp-report-note">{section?.error ? `Unavailable — request failed: ${section.error}` : section?.loading ? "Unavailable — loading at report generation." : section && "data" in section && (!("query" in section) || section.query != null) ? "Unavailable — no response data." : "Not loaded for this report."}</p>;
}
function Issues({ title, values }: { title: string; values?: string[] | null }) {
  return <><h3>{title}</h3>{values == null ? <p>Unavailable</p> : values.length ? <ul>{values.map((value, index) => <li key={`${value}-${index}`}>{value}</li>)}</ul> : <p>None reported by the backend.</p>}</>;
}
function Period({ start, end, timezone }: { start?: string | null; end?: string | null; timezone?: string | null }) {
  return <p>{displayText(start)} to {displayText(end)} (end exclusive) · Timezone: {displayText(timezone)}</p>;
}
export function BuildingPerformanceReport({ snapshot }: { snapshot: BuildingPerformanceReportSnapshot }) {
  const { summary, readiness, charts, applied } = snapshot;
  const config = snapshot.configuration?.siteId === snapshot.siteId && snapshot.configuration.scope === applied.ratingScope ? snapshot.configuration : null;
  const profile = config?.profile?.siteId === snapshot.siteId && config.profile.ratingScope === applied.ratingScope ? config.profile : null;
  const energy = summary.data;
  const rating = readiness.data;
  const period = energy ?? rating;
  const chartData = charts?.siteId === snapshot.siteId && charts.appliedKey === JSON.stringify(applied) ? charts : null;
  const meters = energy?.consumption.meters;
  return <article className="bp-report">
    <header><h1>Building Performance Report</h1><p>{profile?.buildingName ?? snapshot.siteName ?? "Site name unavailable"}</p><p>Site ID: {snapshot.siteId} · Scope: {applied.ratingScope}</p><Period start={period?.periodStart} end={period?.periodEnd} timezone={period?.siteTimezone} /><p>Generated: {snapshot.generatedAt} (UTC). This is report assembly time, not telemetry collection time.</p><p>Calculation inputs: ending month {applied.endingMonth} · {applied.timestampInterpretation} · maximum gap {applied.maxGap}</p><p className="bp-report-note">Target Rating is configuration only. Data Readiness is the backend assessment of inputs and data completeness; this report does not establish a NABERSNZ star rating or certification.</p></header>
    <section><h2>Building profile and configuration</h2>{profile ? <Values rows={[["Building name", profile.buildingName], ["Rentable area", formatMetric(profile.rentableAreaM2, "m²")], ["Weekly occupancy hours", formatMetric(profile.weeklyOccupancyHours)], ["Computer count", formatMetric(profile.computerCount)], ["Target Rating — configuration only", formatMetric(profile.targetRating)], ["Assessment enabled", profile.assessmentEnabled ? "Yes" : "No"]]} /> : config?.missing ? <p>No profile exists for this scope.</p> : <Unavailable section={config} />}<p>Configuration is the loaded current configuration, not a historical configuration snapshot for the reporting period.</p></section>
    <section><h2>Energy performance summary</h2>{energy ? <><Period start={energy.periodStart} end={energy.periodEnd} timezone={energy.siteTimezone} /><Values rows={[["Total energy", formatMetric(energy.consumption?.totalEnergyKwh, "kWh")], ["Energy intensity", formatMetric(energy.energyIntensityKwhPerM2, "kWh/m²")], ["Target Rating — configuration only", formatMetric(energy.targetRating)], ["Data coverage", formatMetric(energy.consumption?.dataCoveragePercent, "%")], ["Total source", displayText(energy.consumption?.totalSource)]]} /><Issues title="Summary quality issues" values={energy.consumption?.qualityIssues} /></> : <Unavailable section={summary} />}</section>
    <section><h2>{rating ? displayText(rating.label) : "Data readiness"}</h2>{rating ? <><Period start={rating.periodStart} end={rating.periodEnd} timezone={rating.siteTimezone} /><Values rows={[["Status", displayText(rating.status)], ["Energy completeness", displayText(rating.energyCompleteness)], ["Coverage", formatMetric(rating.dataCoveragePercent, "%")]]} /><p>{displayText(rating.reason)}</p><h3>Readiness policy</h3><Values rows={[["Policy ID", displayText(rating.readinessPolicy?.id)], ["Options source", displayText(rating.readinessPolicy?.optionsSource)], ["Completeness rule", displayText(rating.readinessPolicy?.completenessRule)], ["Meaning", displayText(rating.readinessPolicy?.meaning)]]} /><Issues title="Readiness quality issues" values={rating.qualityIssues} /><Issues title="Readiness gap flags" values={rating.gapFlags} /></> : <Unavailable section={readiness} />}</section>
    {(["monthly", "annual"] as const).map(kind => { const section = chartData?.[kind]; return <section key={kind}><h2>{kind === "monthly" ? "Monthly trend" : "Annual trend — annual totals"}</h2>{section?.data && section.query ? <BuildingPerformanceTrendChart printMode results={section.data} from={section.query.from} to={section.query.to} kind={kind} /> : <Unavailable section={section} />}</section>; })}
    <section><h2>Energy breakdown</h2>{chartData?.breakdown.data ? <><BuildingPerformanceBreakdownChart printMode result={chartData.breakdown.data} /><Issues title="Breakdown quality issues" values={chartData.breakdown.data.qualityIssues} /></> : <Unavailable section={chartData?.breakdown} />}</section>
    <section><h2>Meter performance</h2>{meters ? <><p>Meter values from the energy summary reporting period.</p><table><thead><tr>{["Meter ID / category", "Allocation (%)", "Energy (kWh)", "Coverage (%)", "Resets", "Quality issues"].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{meters.map(m => <tr key={m.energyMeterId}><th scope="row">{m.energyMeterId}<br />{m.category}</th><td>{formatMetric(m.allocationPercent)}</td><td>{formatMetric(m.energyKwh)}</td><td>{formatMetric(m.dataCoveragePercent)}</td><td>{formatMetric(m.resetCount)}</td><td>{m.qualityIssues?.join(", ") || "None reported"}</td></tr>)}</tbody></table>{meters.length === 0 && <p>No meters returned.</p>}</> : <Unavailable section={summary} />}
    <h3>Meter readiness</h3>{rating?.meters ? <ul>{rating.meters.map(m => <li key={m.energyMeterId}>{m.energyMeterId} · {m.category} · {m.energyCompleteness} · Energy: {formatMetric(m.energyKwh, "kWh")} · Coverage: {formatMetric(m.dataCoveragePercent, "%")} · Allocation: {formatMetric(m.allocationPercent, "%")} · Resets: {formatMetric(m.resetCount)}<Issues title="Meter quality issues" values={m.qualityIssues} /><Issues title="Meter gap flags" values={m.gapFlags} /></li>)}</ul> : <Unavailable section={readiness} />}
    <h3>Loaded meter assignments</h3>{config && profile && !config.assignmentError && !config.loading ? <>{config.assignments.length ? <table><thead><tr>{["Meter ID", "Category", "Included", "Allocation (%)", "Notes"].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{config.assignments.map(m => <tr key={m.id}><th scope="row">{m.energyMeterId}</th><td>{m.consumptionCategory}</td><td>{m.included ? "Yes" : "No"}</td><td>{formatMetric(m.allocationPercent)}</td><td>{displayText(m.notes)}</td></tr>)}</tbody></table> : <p>No assignments returned.</p>}</> : <Unavailable section={config ? { loading: config.loading, error: config.assignmentError ?? config.error } : null} />}</section>
    <section><h2>Requirements</h2>{rating?.requirements ? <>{rating.requirements.length ? <table><thead><tr>{["Code / field", "Outcome / blocking", "Reason", "Meter ID"].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{rating.requirements.map((r, i) => <tr key={`${r.code}-${i}`}><th scope="row">{r.code}<br />{r.field}</th><td>{r.outcome}<br />{r.blocking}</td><td>{displayText(r.reason)}</td><td>{displayText(r.energyMeterId)}</td></tr>)}</tbody></table> : <p>No requirements returned.</p>}</> : <Unavailable section={readiness} />}</section>
    <section><h2>Limitations</h2>{rating?.limitations ? rating.limitations.length ? <ul>{rating.limitations.map((l, i) => <li key={`${l.code}-${i}`}><strong>{l.code}</strong>: {l.reason}</li>)}</ul> : <p>No limitations returned.</p> : <Unavailable section={readiness} />}</section>
  </article>;
}
